version: "3.8"

services:
  kreskayit:
    build: .
    container_name: kreskayit-container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - sqlite_data:/app/instance
    command: python app.py
    restart: unless-stopped
    env_file:
      - .env

volumes:
  sqlite_data:
